title: 📄-as-⚡
description: For devs bored to tears by docs who need to learn them anyways 😭
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Repository: https://github.com/asa55/docs-as-flashcards/
